create db schema (migration, model, factory)
Glints-007/absensi-BE pull request #1
Opened 2021-09-15 07:34 UTC by andranugraha

Did you write good & comprehensive specs? ⭐️
no
What's this PR do ? ⭐️
create migration for db and model relation
What are the relevant tickets ? ⭐️
https://www.notion.so/prawito/Create-default-schema-for-backend-5d569a56cfdd4ccc9ad12a962acf65d0
Where should the reviewer start ?
migrations in database and User, Office and Clock model
How should this be manually tested ?

What is the Dockup URL ?

Any background context you want to provide ?
no
Any deployment note (migrations, new envs, rake tasks, cron) ?
run php artisan migrate to migrate
Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/73644729/133390521-7f33f418-1ebd-4de0-b57d-f6486f9204d7.png)
![image](https://user-images.githubusercontent.com/73644729/133390561-c63a0e7d-f2e3-4b6c-a67e-d618e0f75e2d.png)
![image](https://user-images.githubusercontent.com/73644729/133390587-3030fe23-eee1-4c01-a765-f03bc457a4d1.png)

Definition of Done:

[ X] Specs / Tests are adequate ? ⭐️

[ X] Changes conform with code quality tools (Rubocop, Reek, Brakeman) ? ⭐️

[ Y] Does this PR require Database changes ?

[ X] Does this PR require monitoring after deployment (Scout, logs, Sentry, etc) ?

[ X] Does this PR require a regression test by QA ? All fixes require a regression test.

[ X] Does this add new dependencies ? (network setup, new 3rd party services)

2021-09-15 07:45 UTC, rahmatullah5 requested changes
We need a user/admin seeder so we can populate the default admin data.

2021-09-15 08:18 UTC, andranugraha commented
Seeder for user and office has been created, and I also elaborate changes for timezone. run php artisan config:clear before migrate

2021-09-15 13:28 UTC, rahmatullah5 approved these changes

2021-09-16 04:02 UTC, herulhidayat approved these changes

2021-09-16 04:06 UTC, chaterinamf approved these changes

2021-09-16 05:26 UTC, fknraini approved these changes

2021-09-16 05:28 UTC, merged